### PR TITLE
Implemented ability to retrieve charts over different & longer periods

### PR DESCRIPTION
**Pull request by Borewit**
Implements issue #80

- [x] Recursive downloads to retrieve data over a period longer then one year
- [x] Select period via URL query
- [x] Rename periodLength to interval
- [x] Don't query before 2015-01-10
- [x] Query in npmjs API in UTC

### CODE REVIEW

**Comment by Borewit** [comment]
I added the following options

| argument | default | description |
|----------|---------|------------------------|
| start    | 365     | First day in chart, 10 would be 10 days before the last day |
| end      | 0       | Last day in chart |

Select a 900 period until today:
```URL
http://localhost:9001/compare/music-metadata,jsmediatags,musicmetadata,node-id3,music-metadata-browser,mp3-parser,browser-id3-writer,id3-parser?periodLength=30&start=900`
```

I would consider renaming `periodLength` to `interval` or `tickLength`.

**Comment by cheapsteak** [comment]
Oh man that's awesome!
https://deploy-preview-81--npmcharts.netlify.com/?start=900
And great idea, renaming `periodLength` to `interval` makes total sense 🙏

**Comment by cheapsteak** [comment]
Ack crap but that might break existing links. Not sure if it's worth adding code complexity to alias
Maybe leave it? What do you think?

**Comment by Borewit** [comment]
> Ack crap but that might break existing links in.

Indeed, that's why I asked.

Maybe rename it, and support backwards compatibility at the same time, to prevent stored URLs from breaking.

**Comment by cheapsteak** [comment]
If you don't mind the trouble, yes please, rename and alias sounds great 🙏

**Comment by Borewit** [comment]
Please check and test carefully, if you are happy, you can merge,

**Comment by cheapsteak** [comment]
Thanks again for the incredibly thorough PR
This looks _really_ cool
https://deploy-preview-81--npmcharts.netlify.com/compare/react,angular,@angular/core,ember-cli,vue?start=1200

**Pull request merged**
