### PR TITLE
updgraded puppeteer to 5.3.1

### LINKED ISSUE #123: Upgrade puppeteer to v5
The server uses puppeteer to generate screenshots

It currently uses [puppeteer@2.1.1](https://github.com/cheapsteak/npmcharts.com/blob/7ed63078471a779f8049fe560bceae897553fad7/packages/server/package.json#L21)

The latest version is currently [5.3.1](https://www.npmjs.com/package/puppeteer)

Would be useful to upgrade and see if anything's broken (hoping it might just work)

To test, run the server by `cd package/server && npm start`, then navigate to `http://localhost:3896/chart-image/vue.png`, wait for it to load (takes a while), and see if a chart comes back. If yes, we're good to go; if not, might need to do some debugging

### PR DESCRIPTION
**Pull request by Aditya-ds-1806**
Upgraded puppeteer to latest version 5.3.1 without any errors. The page http://localhost:3896/chart-image/vue.png does open up and the screenshot is generated as expected. This fixes #123

### CODE REVIEW

**Comment by Aditya-ds-1806** [comment]
@cheapsteak is this PR fine? It should I add more details?

**Comment by cheapsteak** [comment]
@Aditya-ds-1806 thanks! this should have resulted in a change in the [yarn.lock](https://github.com/cheapsteak/npmcharts.com/blob/master/packages/server/yarn.lock) file, would you mind checking that in as well?

**Comment by Aditya-ds-1806** [comment]
I actually used npm install v5.3.1. forgot about the yarn.lock file. Will commit it now

**Comment by Aditya-ds-1806** [comment]
Sorry I'm not familiar with yarn. Which yarn.lock file is supposed to change? The one inside the server for right? Or both? I ran `yarn add puppeteer@5.3.1`

**Comment by cheapsteak** [comment]
haha yeah sorry I wonder how that happened, whichever one changes is good!

**Comment by Aditya-ds-1806** [comment]
Oh ok. The yarn.lock file in the root changed. But the yarn.lock inside the server/packages didn't change. It still says 2.1.1 for version number

**Comment by cheapsteak** [comment]
that sounds fine, please commit the one in root we should be good!

(I should maybe delete the yarn.lock in server, that probably shouldn't be there XD)

**Comment by Aditya-ds-1806** [comment]
All right, I committed the root file

**Comment by cheapsteak** [comment]
thanks so much!

**Comment by Aditya-ds-1806** [comment]
Thanks to you too!!

**Pull request merged**
