### PR TITLE
fix weird y-axis ticks

### PR DESCRIPTION
**Pull request by Xiaohanxu1996**
to fix issue #130

### CODE REVIEW

**Review by cheapsteak — CHANGES_REQUESTED** [review]
woot! thank you very much

I'm not very much used to reading numbers in exponential format though, translating 10^7 into a number I recognize takes a lot of work, would you mind formatting the number be the same as linear scale with "k"s and "M"s?

**Comment by Xiaohanxu1996** [comment]
no problem, I will submit another pr later.

**Comment by Xiaohanxu1996** [comment]
@cheapsteak  seems CI/CD is broken ?

**Review by cheapsteak — APPROVED** [review]
looks great, thanks very much!  

and yeah look like CI is a bit bugged, will look into it 👀

**Pull request merged**
