### PR TITLE
added instructions to set up project locally and test code

### LINKED ISSUE #129: Add instructions to set up the project locally
I myself faced a few problems with (npm and yarn) while setting up the project locally. This will save other's time and will help them get started easily. I would like to take this issue and add a section in the readme.md file.

### PR DESCRIPTION
**Pull request by Aditya-ds-1806**
@cheapsteak Did I miss anything?  Fixes #129

### CODE REVIEW

**Comment by cheapsteak** [comment]
@Aditya-ds-1806 thank you! mind if I push some changes to your branch?

**Comment by Aditya-ds-1806** [comment]
No issues!

**Comment by cheapsteak** [comment]
oh nvm your branch is good! the problem is with the repo's local setup process at the moment (shouldn't need to run yarn twice, wish I could remember why this got this way), but that can be fixed separately   

merging this in

thank you!

**Comment by cheapsteak** [comment]
yup!

**Pull request merged**
